### PR TITLE
build for windows

### LINKED ISSUE #1: Windows build
Previous attempt in https://github.com/conda-forge/staged-recipes/pull/6080; osqp assumes MinGW on Windows, it seemed to compile okay with a bit of a patch but needs a little more fiddling.

### PR DESCRIPTION
**Pull request by h-vetinari**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

closes #1 

~Also added `cmake` to runtime dependencies for the codegen-interface,~ the tests of which are now enabled as well.

Builds locally for me on windows, but labeling this as WIP until linux/macos comes through as well...

### CODE REVIEW

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
@conda-forge/help-python-c 

Hey everyone; I was wondering if someone can help me debug this recipe. I manage to build this locally with VS2017, but on the azure machines it crashes with:
```
  [...]
  running build_ext
  CMake Error at CMakeLists.txt:5 (project):
    Failed to run MSBuild command:
  
      MSBuild.exe
  
    to get the value of VCTargetsPath:
  
      Microsoft (R) Build Engine version 4.8.3761.0
      [Microsoft .NET Framework, version 4.0.30319.42000]
      Copyright (C) Microsoft Corporation. All rights reserved.
```

Any pointers or help very much appreciated. :)

**Comment by xhochy** [comment]
Use `NMake Makefiles` as the CMake generator. This should fix the mentioned issue.

**Comment by h-vetinari** [comment]
Thanks for the tip and the quick response @xochy, that did indeed solve it (after a few tries).

**Comment by h-vetinari** [comment]
This is out of WIP now. I'm letting the CI confirm that this runs through separately (before pushing the commit that enables the codegen-tests), now that I've force-pushed to clean up some commit messages.

I'll leave this open for a few days for you to review @dougalsutherland. I tried to keep the patches absolutely minimal for passing the CI.

However, since cmake & the compilers are not a runtime dependency, it might make sense to add a warning to `codegen` that the respective dependencies can be installed with `conda install -c conda-forge cmake compilers`

**Comment by h-vetinari** [comment]
> @dougalsutherland: Thanks for this @h-vetinari! Sorry I wasn't responding, was in the process of a complicated move and then vacation. :)

No worries! Once you'll have some more time, feel free to join us trying to unblock the windows builds in #12. :)

**Pull request merged**
