### PR TITLE
Enable ppc64le and update to 0.6.1

### PR DESCRIPTION
**Pull request by jayfurmanek**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Enable building for ppc64le arch using Travis CI

### CODE REVIEW

**Comment by jayfurmanek** [comment]
@conda-forge-admin, please rerender

**Comment by jayfurmanek** [comment]
@conda-forge-admin, please rerender

**Comment by jayfurmanek** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
Hey @jayfurmanek 
Cool that you're enabling ppc64le builds!

I have to admit that it's an architecture that's new to me, and I wouldn't know how to debug it if problems were to arise. For example, we're currently struggling to debug the windows builds in #11 / #12, and I'm hesitant to add something to the CI that might get us similarly stuck.

As such, I'd ask you to try if you can get this branch (or better: a new PR) to work also with [these](https://github.com/conda-forge/osqp-feedstock/pull/12/commits/d3a9c15c67436c33c15f489c3b44765da8c2b9dd) [two](https://github.com/conda-forge/osqp-feedstock/pull/12/commits/2d7fa853486c87b7622c3c179feb5f5cfaaf0f95) commits, and see if ppc64le would work there.

Furthermore, if you're willing to take care of ppc64le-builds, it would be reassuring to have you in the list of recipe maintainers (in this case, just add your GH-handle at the end of `meta.yaml`), so you'd hopefully help us get unstuck if ppc64le-builds were to fail in the future.

PS. What's the reason for adding `make` (beyond debugging the build) if there is one? Not sure how `make`/`cmake` behave differently on different platforms, but at least on non-ppc64le-systems we shouldn't need `make`. (i.e. add `  # [ppc64le]` after `make`).

**Comment by h-vetinari** [comment]
OK, that's cool. How about you revert this PR to 0.5.0 (sorry for the churn, but you didn't open a separate PR for trying 0.6.1), and then we rebase #12 on that (and can keep trying to fix the windows problems there)? At least then there would be a build for ppc64le already.

**Comment by jayfurmanek** [comment]
Sounds good. I put up: https://github.com/conda-forge/osqp-feedstock/pull/15

**Pull request closed without merging**
