### PR TITLE
osqp v0.6.1

### PR DESCRIPTION
**Pull request by h-vetinari**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Seems there was a very quick bugfix release of 0.6.1 after 0.6.0.

Closes #11 (if everything runs through)

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by bstellato** [comment]
@conda-forge-admin, please rerender

**Comment by bstellato** [comment]
@h-vetinari I have tried to push to the branch `0.6.1` of your fork but I do not have permissions. Is there any change I need to be able to push?

**Comment by h-vetinari** [comment]
@bstellato 
Hey, I thought you'd have the rights as well, to be honest. In any case, you can push to the branches of `regro-cf-autotick-bot` (like I did in #11).

I'll try to add you as a collaborator to my fork, then you should definitely have the push rights.

**Comment by bstellato** [comment]
Ok Thanks! It worked.

**Comment by bstellato** [comment]
@conda-forge/help-python-c does anyone know why the windows build is always failing? I am not sure why it is always trying to link against the debug version of Python. It would be great to have `0.6.1` on conda-forge so that we can change the main website documentation and redirect all the downloads to the conda-forge channel.

**Comment by bstellato** [comment]
@conda-forge-admin, please rerender

**Comment by bstellato** [comment]
Now the "debug" issue should be fixed. However, it still fails with codegen on windows [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=71417&view=logs&jobId=171a126d-c574-5c8c-1269-ff3b989e923d&taskId=7225e372-3a5e-5b11-c153-719d50bbeacd&lineStart=1260&lineEnd=1261&colStart=1&colEnd=1). It is very weird. It says that there is an unmatched parenthesis but every other platform is fine. Can it be related to NMake on windows? Is there a reason why we are not just sticking with CMake on windows?

**Comment by h-vetinari** [comment]
@bstellato 
Cool that you fixed the issue with the debug-build! Unmatched parentheses sounds more tractable I guess...? Could it be that MVSC is less permissive or has a bug?

**Comment by h-vetinari** [comment]
> Can it be related to NMake on windows? Is there a reason why we are not just sticking with CMake on windows?

To be honest, I don't know. I only changed to NMake at the advice of @xhochy, because I was running into [troubles](https://github.com/conda-forge/osqp-feedstock/pull/10#issuecomment-525947008) when trying to build for windows. But I guess there's no reason we couldn't try to go back to CMake.

**Comment by bstellato** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
@conda-forge/core 
Hey, we just added ppc64le support in another PR, and after merging master here, a rerender removes those CI jobs again. Seems like a conda smithy bug?

(also, if someone has the time to have a look at our windows builds, which we can't get to run with neither NMake nor CMake).

**Comment by isuruf** [comment]
You have a bad merge. See https://github.com/conda-forge/osqp-feedstock/blob/master/conda-forge.yml#L6-L9

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
@isuruf 
Thanks a lot for the quick response! :)

If you have time, it would help us a lot if you could have a look at our windows jobs - we haven't been able to debug the MVSC / NMake / CMake interactions.

**Comment by isuruf** [comment]
In azure, CMake with Visual Studio generator doesn't work. You need to use NMake Makefiles or Ninja generator.

**Comment by h-vetinari** [comment]
@isuruf 
Thanks, we know that (but admittedly didn't know why exactly), however we also run into errors with NMake: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=71417&view=logs&jobId=171a126d-c574-5c8c-1269-ff3b989e923d

**Comment by h-vetinari** [comment]
@isuruf 
I reverted back to reinstate NMake - we had experimented with going back to CMake after being puzzled that MVSC complains about a mismatched parenthesis (for code that runs on all other platforms; when compiled with NMake):
```
d:\bld\osqp_1568619494774\test_tmp\code2\include\glob_opts.h(110): fatal error C1012: unmatched parenthesis: missing ')'
```

**Comment by h-vetinari** [comment]
Superseded by #17 / #18

**Pull request closed without merging**
