### PR TITLE
bump to 0.6.2

### PR DESCRIPTION
**Pull request by h-vetinari**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Since the migrator hasn't come past yet, do it manually

### CODE REVIEW

**Comment by h-vetinari** [comment]
Aside from the missing aarch-builds for `qdldl-python` (see https://github.com/conda-forge/qdldl-python-feedstock/pull/7), this should be ready. Can you please have a look @bstellato @gbanjac ?

**Comment by bstellato** [comment]
It looks great to me! Thanks a lot @h-vetinari for the help with the new release. Just a couple of questions: 

- is Python 3.9 supported? It seems to me the azure builds are up to Python 3.8
- I am not sure why some of the tests (in particular drone CI) are failing. I am not familiar with it though.
- Regarding Travis CI, is it still used in conda-forge? I have seen many projects are transitioning to github actions.

**Comment by h-vetinari** [comment]
Hey @bstellato, thanks for the feedback!

>     * is Python 3.9 supported? It seems to me the azure builds are up to Python 3.8

#24 had failing tests (those happened across all current PRs on 0.6.1 for reasons I could not determine); as soon as this PR is through, I'll rebase #24 and that shouldn't be an issue.


>     * I am not sure why some of the tests (in particular drone CI) are failing. I am not familiar with it though.

These aren't failing tests, just missing dependencies because `qdldl-python` hadn't been built for aarch yet (but solved by https://github.com/conda-forge/qdldl-python-feedstock/pull/7, for which master is currently building)

>     * Regarding Travis CI, is it still used in conda-forge? I have seen many projects are transitioning to github actions.

It's still in use for ppc64le builds. Not sure what agreement was reached between conda(-forge) and travis, but all transitioning projects (that I know of) only do so because the free tier has way too little CI capacity to support development.

**Comment by h-vetinari** [comment]
If you restart this PR in about an hour (once the builds on for qdldl are through and the builds have reached the server cache), the CI should go green, and the PR can be merged - just in my timezone it's a bit late already to wait for that. ;-)

**Comment by h-vetinari** [comment]
Unfortunately, we have what looks like real test errors on ppc64le (aarch still didn't pick up the dependency):
```
=========================== short test summary info ============================
FAILED tests/basic_test.py::basic_tests::test_basic_QP - AssertionError: 
FAILED tests/basic_test.py::basic_tests::test_update_bounds - AssertionError: 
FAILED tests/basic_test.py::basic_tests::test_update_l - AssertionError:
FAILED tests/basic_test.py::basic_tests::test_update_q - AssertionError: 
FAILED tests/basic_test.py::basic_tests::test_update_u - AssertionError: 
FAILED tests/feasibility_test.py::feasibility_tests::test_feasibility_problem
FAILED tests/polishing_test.py::polish_tests::test_polish_random - AssertionE...
FAILED tests/polishing_test.py::polish_tests::test_polish_simple - AssertionE...
FAILED tests/polishing_test.py::polish_tests::test_polish_unconstrained - Typ...
FAILED tests/unconstrained_test.py::unconstrained_tests::test_unconstrained_problem
FAILED tests/update_matrices_test.py::update_matrices_tests::test_solve - Ass...
FAILED tests/update_matrices_test.py::update_matrices_tests::test_update_A - ...
FAILED tests/update_matrices_test.py::update_matrices_tests::test_update_A_allind
FAILED tests/update_matrices_test.py::update_matrices_tests::test_update_P - ...
FAILED tests/update_matrices_test.py::update_matrices_tests::test_update_P_A_allind
FAILED tests/update_matrices_test.py::update_matrices_tests::test_update_P_A_indA
FAILED tests/update_matrices_test.py::update_matrices_tests::test_update_P_A_indP
FAILED tests/update_matrices_test.py::update_matrices_tests::test_update_P_A_indP_indA
FAILED tests/update_matrices_test.py::update_matrices_tests::test_update_P_allind
================== 19 failed, 33 passed, 1 skipped in 25.76s ===================
```

I'm still going to merge this, and we can figure out aarch support independently of #24 an #26.

**Pull request merged**
