### PR TITLE
Re-enable codegen tests on windows

### PR DESCRIPTION
**Pull request by h-vetinari**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Second part of replacing #12 - re-enabling the codegen tests on windows. Note this is based on #17 and only contains one extra commit on top of that.

### CODE REVIEW

**Comment by bstellato** [comment]
Thanks for this! I think it would be best to keep using cmake as in the other interfaces for consistency and ease of maintenance. I know it caused issues as in https://github.com/conda-forge/osqp-feedstock/pull/10#issuecomment-525947008 but I hope we can solve them.

**Comment by h-vetinari** [comment]
> @bstellato: Thanks for this! I think it would be best to keep using cmake as in the other interfaces for consistency and ease of maintenance. I know it caused issues as in #10  but I hope we can solve them.

Unfortunately, I believe this will not be possible. I didn't know the inner workings of the whole azure vs. make vs. MVSC, but I consider the following [statement](https://github.com/conda-forge/osqp-feedstock/pull/12#issuecomment-531658166) from one of the core conda folks in #12 to be definite:

> @isuruf: In azure, CMake with Visual Studio generator doesn't work. You need to use NMake Makefiles or Ninja generator.

That doesn't mean it can't be solved, of course, but I believe we're gonna have to be patient for people from conda-forge who know the compiler infrastructure to help us there (or figure out what's so special about codegen vs. windows).

Incidentially, the original author of the conda-forge feedstock-recipe for osqp, @dougalsutherland, is in both `@conda-forge/help-python-c` and `@conda-forge/core`, but has been very busy recently (although sometimes seen by the odd emoji here and there ;-)).

**Comment by h-vetinari** [comment]
I can see that the log contains
```
%SRC_DIR%>SET "CMAKE_GENERATOR=Visual Studio 14 2015 Win64"  
```
just before the codegen tests fail, which seems to contradict the recommendation to use NMake. However, I can't find in the source code (nor the conda setup) where this variable is set...?

**Comment by bstellato** [comment]
Isn't it happening here? https://github.com/oxfordcontrol/osqp-python/blob/39aa8baf306b5f24a4b7d66cb0d979817a79c13f/setup.py#L24

**Comment by h-vetinari** [comment]
@bstellato 
Unfortunately not, as that occurrence is already being taken care of by [patch 0001](https://github.com/conda-forge/osqp-feedstock/blob/master/recipe/patches/0001-setup-use-NMake-on-windows.patch)...

**Comment by h-vetinari** [comment]
At long last, this now magically passed again. 🥳

**Comment by bstellato** [comment]
That's great. The mysteries of CI... Glad it is working now!

**Pull request merged**
